@host=http://127.0.0.1:8081
@cookie=bookauth=uo4Ka6jJb6qrWbhOO8Pa3Xzqvz81tUMH7oa5xMGp9ErBKjVBADpl5MedF6fl83yQqITIRWL0WqHn8prxtpa8xACUEhMmVOaIqbIJQLkBkl0Hla4pGue1EHM=
###
GET {{host}}/course/G100005701
cookie: {{cookie}}

###
GET {{host}}/courses?offset=0&keyword=
cookie: {{cookie}}
###
GET {{host}}/login?return_to=/
Cookie: ory_kratos_session=MTY2NTM5NTE4N3xTNmRXWGFJcF8wVmJObnp3YXl5UEY1cG13aktRcnQzdUZHZmNvSmJwUl9faUdBOUNwS1ptc3lyY1lsVkxfT29LZHVfRXRrVUNVVFlaaUlhWnpnR0JfSEMxQnVqTEVacjZtZU1iOVFBdTRXQ2tYVHBYeC13YU9nWW5BRm55NWVjOHVKWkFxZlkxQlE9PXwIjKssppgD77e4yYmMWX6x5qW95UKgEJqywFqcH4viqQ==
###
GET {{host}}/me
cookie: {{cookie}}
###
GET {{host}}/article/L1029/comments
###
GET http://127.0.0.1:8081/test
cookie: {{cookie}}
